### ISSUE TITLE
JSON QS

### ISSUE THREAD

**Issue by DanieleGrimaldi** [tmaurie/hello-f1-vue#1]
Hi, I'm a student and I'm doing a project to do a calendar with the results of the f1. I am searching a file json with the results but I can't find it. Can you tell me where did you find it? Thanks

**Comment by tmaurie** [comment]
Hi,  all of the results come from consuming [http://ergast.com/mrd/](http://ergast.com/mrd/) API.

For example, you'll want to use [https://ergast.com/api/f1/current/last/results.json](https://ergast.com/api/f1/current/last/results.json) for getting the latest results
